name: Lint test
on: [push]

env:
  BUILD_TYPE: Debug

jobs:
#  lint_test:
#    runs-on: ubuntu-latest
#    name: Code check
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./myaction

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build
        shell: bash

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13

      - name: Configure Cmake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=/usr/bin/clang++

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          sudo find -executable -type f -name "test_*" | bash
          ls
          find . -name "results.txt" -print | zip results.zip -@

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{runner.workspace}}/artifact.zip
          retention-days: 1
