name: AIO Pipeline
on: [ push ]

env:
  BUILD_TYPE: Debug
  BUILD_REP: cmake-build-debug

jobs:
  on_commit:
    runs-on: ubuntu-latest
    steps:
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}

          Repository: ${{ github.repository }}

          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

  lint_test:
    runs-on: ubuntu-latest
    needs: on_commit
    name: code_check
    steps:
      - uses: actions/checkout@v2
      - uses: ./myaction

  build_and_test:
    runs-on: ubuntu-latest
    needs: lint_test
    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/$BUILD_REP
        shell: bash

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13

      - name: Configure Cmake
        shell: bash
        working-directory: ${{runner.workspace}}/${{env.BUILD_REP}}
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=/usr/bin/clang++

      - name: Build
        working-directory: ${{runner.workspace}}/${{env.BUILD_REP}}
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/${{env.BUILD_REP}}
        shell: bash
        run: |
          sudo find -executable -type f -name "test_*" | bash
          find . -name "results.txt" -print | zip results.zip -@

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{runner.workspace}}/${{env.BUILD_REP}}/results.zip
          retention-days: 1

  on_finish:
    needs: build_and_test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts for build_and_test
        uses: actions/download-artifact@v3
        with:
          name: results

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ succeed() && 'The job has succeeded.' || 'The job has failed.' }}
          document: results.zip
